FROM python:3.12-slim


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /backend

# Copy project files
COPY . /backend


RUN uv sync --frozen --no-cache
RUN uv pip install ".[test]"
# Create data directories
RUN mkdir -p /mnt/oxn-data/experiments


# Default command runs tests
CMD ["uv", "run","pytest", "tests/", "-v"] 